server:
  port: 7027
spring:
  profiles:
    active: dev
  application:
    name: kq-oauth2-authentication-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
management:
  endpoints:
    web:
      exposure:
        include: "*"

# 自定义授权的应用
kq:
  oauth2:
    clients[0]: # 第一个应用，要是有多个clients[1]、clients[2]等等
      clientId: client-app
      clientSecret: 123456
      accessTokenValiditySeconds: 7200
      authorizedGrantTypes: refresh_token,password # authorization_code,
      scopes: all,read,write