server:
  port: 7031
spring:
  profiles:
    active: dev
  application:
    name: kq-oauth2-api
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"