server:
  port: 7019
spring:
  application:
    name: admin-client
  boot:
    admin:
      client:
        url: http://127.0.0.1:7016 #配置到 admin-server 地址，让admin-server对admin-client进行监控
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848


#### 暴露端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  file:
    name: admin-client.log #添加开启admin的日志监控
  pattern:
    ####日志高亮
    file: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx'
